title: LMS QA Wiki
remote_theme: just-the-docs/just-the-docs
color_scheme: light

# GitHub Pages
plugins:
  - jekyll-remote-theme

# Optional: logo and favicon
# logo: "/assets/logo.png"
# favicon_ico: "/assets/favicon.ico"
